# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GeneralExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GeneralExample

    pod 'FMDB', '2.7.2' #使用固定版本2.7.2

  target 'GeneralExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GeneralExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
