# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GeneralExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GeneralExample

  pod 'SwiftyJSON', '~> 4.1.0'
  
  pod 'ObjectMapper', '~> 3.3.0'

  pod 'WCDB.swift'

  target 'GeneralExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GeneralExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
